# Loki configuration for log aggregation
# @author Terraform DevOps
# @date 2025-01-15

auth_enabled: false

server:
  http_listen_port: ${LOKI_HTTP_PORT}
  grpc_listen_port: ${LOKI_GRPC_PORT}
  log_level: ${LOKI_LOG_LEVEL}

common:
  path_prefix: ${LOKI_STORAGE_PATH}
  storage:
    filesystem:
      chunks_directory: ${LOKI_STORAGE_PATH}/chunks
      rules_directory: ${LOKI_STORAGE_PATH}/rules
  replication_factor: ${LOKI_REPLICATION_FACTOR}
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_scheduler:
  max_outstanding_requests_per_tenant: 32768

frontend:
  max_outstanding_per_tenant: 32768

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true

# Analytics configuration
analytics:
  reporting_enabled: ${LOKI_ANALYTICS_ENABLED}

# Limits configuration
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  max_query_parallelism: ${LOKI_MAX_QUERY_PARALLELISM}
  max_streams_per_user: ${LOKI_MAX_STREAMS_PER_USER}
  max_line_size: ${LOKI_MAX_LINE_SIZE}
  max_query_length: ${LOKI_MAX_QUERY_LENGTH}
  max_query_series: ${LOKI_MAX_QUERY_SERIES}
  max_entries_limit_per_query: ${LOKI_MAX_ENTRIES_LIMIT_PER_QUERY}
  max_streams_matchers_per_query: 1000
  max_concurrent_tail_requests: 10
  allow_structured_metadata: false

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h # 14 days

compactor:
  working_directory: /loki
  compaction_interval: 10m
  retention_enabled: false
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
