# GitHub Actions workflow for Terraform plan
# @author Terraform DevOps
# @date 2025-01-15

name: 'Terraform Plan'

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/terraform-plan.yml'

env:
  TF_VERSION: '1.6.0'

jobs:
  plan:
    name: 'Plan Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./

    - name: Terraform Plan
      run: terraform plan -no-color
      working-directory: ./

    - name: Comment Plan on PR
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const output = `#### Terraform Plan 📖
          
          \`\`\`
          ${process.env.PLAN || 'No changes'}
          \`\`\`
          
          *Pusher: @${context.actor}, Action: \`${context.eventName}\`*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
      env:
        PLAN: ${{ steps.plan.outputs.stdout }}
