# GitHub Actions workflow for Terraform Destroy
# @author Terraform DevOps
# @date 2025-01-15

name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm infrastructure destruction'
        required: true
        default: ''

env:
  TF_VERSION: '1.6.0'

jobs:
  destroy:
    name: 'Destroy Terraform Infrastructure'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Confirm Destruction
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "destroy" ]; then
          echo "❌ Destruction not confirmed. Please type 'destroy' to confirm."
          exit 1
        fi
        echo "✅ Destruction confirmed. Proceeding with terraform destroy..."

    - name: Terraform Init
      run: terraform init -upgrade
      working-directory: ./

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./

    - name: Notify Destruction Complete
      run: |
        echo "🗑️ Terraform destroy completed successfully!"
        echo "⚠️ All infrastructure has been destroyed!"
        echo "💡 Remember to clean up any remaining Docker volumes if needed."