# GitHub Actions workflow for Terraform apply
# @author Terraform DevOps
# @date 2025-01-15

name: 'Terraform Apply'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - prod
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

env:
  TF_VERSION: '1.6.0'

jobs:
  apply:
    name: 'Apply Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./

    - name: Terraform Plan
      if: github.event.inputs.action == 'apply'
      run: terraform plan -no-color -out=tfplan
      working-directory: ./

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve tfplan
      working-directory: ./

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: terraform destroy -auto-approve
      working-directory: ./

    - name: Output Results
      if: github.event.inputs.action == 'apply'
      run: terraform output -json
      working-directory: ./
