# GitHub Actions workflow for Terraform CI/CD Pipeline
# @author Terraform DevOps
# @date 2025-01-15

name: 'Terraform CI/CD'

on:
  push:
    branches: [ main ]
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/**.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/**.yml'

env:
  TF_VERSION: '1.6.0'

jobs:
  terraform:
    name: 'Terraform ${{ matrix.job }}'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        job: [validate, plan, apply]
        include:
          - job: validate
            condition: ${{ always() }}
          - job: plan
            condition: ${{ github.event_name == 'pull_request' }}
          - job: apply
            condition: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format Check
      if: matrix.job == 'validate'
      run: terraform fmt -check -recursive
      working-directory: ./

    - name: Terraform Init
      run: |
        terraform init -upgrade || {
          echo "Provider signature issue detected, clearing cache and retrying..."
          rm -rf .terraform/providers
          terraform init -upgrade || terraform init
        }
      working-directory: ./

    - name: Terraform Validate
      if: matrix.job == 'validate'
      run: terraform validate
      working-directory: ./

    - name: Terraform Plan
      if: matrix.job == 'plan'
      id: terraform-plan
      run: terraform plan -no-color
      working-directory: ./
      continue-on-error: true

    - name: Terraform Apply
      if: matrix.job == 'apply'
      run: terraform apply -auto-approve
      working-directory: ./

    - name: Terraform Output
      if: matrix.job == 'apply'
      run: terraform output
      working-directory: ./

    - name: Comment Plan on PR
      if: matrix.job == 'plan' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const output = `#### Terraform Plan 📖
          
          **Status:** ${{ steps.terraform-plan.outcome }}
          
          \`\`\`
          ${{ steps.terraform-plan.outputs.stdout }}
          \`\`\`
          
          *Pusher: @${context.actor}, Action: \`${context.eventName}\`*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Notify Success
      if: matrix.job == 'apply'
      run: |
        echo "✅ Terraform apply completed successfully!"
        echo "🚀 Observability stack is now deployed!"
        echo "📊 Grafana: http://localhost:3000"
        echo "📈 Prometheus: http://localhost:9090"
        echo "📝 Loki: http://localhost:3100"
